name: BetterDiscord CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 7

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      #    - name: Lint
      #      run: pnpm lint

      #    - name: Run tests
      #      run: pnpm test

      - name: Build asar
        run: pnpm dist

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        if: ${{github.ref == 'refs/heads/main'}} # Only create artifacts when pushed to main
        with:
          if-no-files-found: error
          retention-days: 30
          path: dist/betterdiscord.asar
